apiVersion: fep.fujitsu.io/v1
kind: FEPExporter
metadata:
  name: new-fep-exporter
spec:
  fepExporter:
    sysExtraLogging: false
    sysExtraEvent: true
    image:
      pullPolicy: IfNotPresent
    mcSpec:
      limits:
        cpu: 500m
        memory: 700Mi
      requests:
        cpu: 200m
        memory: 512Mi
    exporterLogLevel: "error"
    fepClusterList:
      - new-fep1
    restartRequired: false
    userCustomQueries: |
      usr_example:
        query: "SELECT EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp())) as lag"
        master: true
        metrics:
          - lag:
              usage: "GAUGE"
              description: "Replication lag behind master in seconds"