{
 "title": "FEP Dashboard-Final",
 "description": "This dashboard works with postgres_exporter for Prometheus.",
 "tags": [
  "postgres",
  "db",
  "stats"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "namespace", "label": "Namespace", "query": "query_result(pg_up)" },
   {
    "name": "exporter",
    "label": "Exporter",
    "query": "query_result(pg_up {namespace=\"$namespace\"} )"
   },
   {
    "name": "dbserver",
    "label": "Database server",
    "query": "query_result(pg_static {service=~\"$exporter-service\"})"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "query_result(pg_database_size_bytes {service=~\"$exporter-service\"})"
   },
   {
    "name": "mode",
    "label": "Lock table",
    "query": "label_values({mode=~\"accessexclusivelock|accesssharelock|exclusivelock|rowexclusivelock|rowsharelock|sharelock|sharerowexclusivelock|shareupdateexclusivelock\"}, mode)"
   }
  ]
 },
 "panels": [
  { "title": "Server Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "description": "Average user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{container=\"fep-patroni\", namespace=\"$namespace\", pod=\"$dbserver\"}[5m]) * 1000)",
     "legendFormat": "$dbserver CPU Time"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "description": "Virtual and Resident memory size in bytes, averages over 5 min interval",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"fep-patroni\", namespace=\"$namespace\", pod=~\"$dbserver\"}!=0",
     "legendFormat": "Mem Working Set"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{container=\"fep-patroni\", namespace=\"$namespace\", pod=~\"$dbserver\"}!=0",
     "legendFormat": "Mem requested"
    }
   ]
  },
  {
   "title": "Database Server - Version, Up time , Parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "name",
     "targets": [
      {
       "expr": "pg_static{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "{{short_version}}"
      }
     ]
    },
    {
     "title": "Database Server Start Time",
     "type": "singlestat",
     "description": "start time of the process",
     "gridPos": { "h": 2, "w": 6, "x": 3, "y": 2 },
     "format": "dateTimeAsLocal",
     "valueName": "avg",
     "targets": [
      {
       "expr": "container_start_time_seconds{namespace=\"$namespace\", container=\"fep-patroni\", pod=\"$dbserver\"} * 1000"
      }
     ]
    },
    {
     "title": "Effective Cache",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{namespace=\"$namespace\", service=\"$exporter-service\",server=~\"$dbserver.*\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_seq_page_cost{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}"
      }
     ]
    },
    {
     "title": "Current update data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_updated{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"})"
      }
     ]
    },
    {
     "title": "Current insert data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_inserted{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"})"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"} /1024/1024"
      }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}"
      }
     ]
    },
    {
     "title": "Current fetch data",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "SUM(pg_stat_database_tup_fetched{namespace=\"$namespace\", datname=~\"$datname\", service=\"$exporter-service\", server=~\"$dbserver.*\"})"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}"
      }
     ]
    },
    {
     "title": "Shared Buffers",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conflicts/Deadlocks",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_deadlocks{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"}",
       "legendFormat": "{{datname}} deadlocks"
      }
     ]
    },
    {
     "title": "Buffers (bgwriter)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}[5m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_alloc{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}[5m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}[5m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}[5m])",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}[5m])",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Temp File (Bytes)",
     "type": "graph",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_temp_bytes{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"}[5m])",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Number of times table Analyze by Autovacuum",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_user_tables_autoanalyze_count{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "{{datname}}:{{relname}}"
      }
     ]
    },
    {
     "title": "Checkpoint Stats",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}[5m])",
       "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
      },
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}[5m])",
       "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"} / (pg_stat_database_blks_read + pg_stat_database_blks_hit)",
       "legendFormat": "{{ datname }}"
      }
     ]
    },
    {
     "title": "Database size",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 25 },
     "repeat": "server",
     "targets": [
      {
       "expr": "pg_database_size_bytes{namespace=\"$namespace\", datname=~\"$datname\" ,service=\"$exporter-service\", server=~\"$dbserver.*\"} /1024/1024  !=0",
       "legendFormat": "$dbserver - {{datname}} "
      }
     ]
    },
    {
     "title": "Lock tables",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "pg_locks_count{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", mode=~\"$mode\"} != 0",
       "legendFormat": "{{datname}}, {{mode}}"
      }
     ]
    },
    {
     "title": "Number of tables without vacuum in last 24 hours",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_capacity_tblvacuum_table_count{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "{{table_schema}}"
      }
     ]
    },
    {
     "title": "Number of checkpoint requests",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_bgwriter_checkpoints_req{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "$dbserver"
      }
     ]
    },
    {
     "title": "Number of auto-vacuum",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_user_tables_autovacuum_count{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "{{relname}}"
      }
     ]
    },
    {
     "title": "Number of live rows",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_user_tables_n_live_tup{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "{{relname}}"
      }
     ]
    },
    {
     "title": "Number of rows updated",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_user_tables_n_tup_upd{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "{{relname}}"
      }
     ]
    },
    {
     "title": "Number of wait events",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_wait_count{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "{{datname}}:{{event}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of transactions lasting longer than 5 minutes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_capacity_longtx_count{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}!=0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "INSERT table data (SELECT)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_user_tables_n_tup_ins{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "{{datname}}:{{relname}}"
      }
     ]
    },
    {
     "title": "Fetched database data",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_fetched{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_xact_commit{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"}[5m])!=0",
       "legendFormat": "{{datname}} commits"
      },
      {
       "expr": "irate(pg_stat_database_xact_rollback{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"}[5m])!=0",
       "legendFormat": "{{datname}} rollbacks"
      }
     ]
    },
    {
     "title": "Table- UPDATED data",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_user_tables_n_tup_hot_upd{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"}",
       "legendFormat": "{{datname}}: {{relname}}"
      }
     ]
    },
    {
     "title": "Return data",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_returned{namespace=\"$namespace\", datname=~\"$datname\", service=\"$exporter-service\", server=~\"$dbserver.*\"\r} != 0",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Dead rows ",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_user_tables_n_dead_tup{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"}",
       "legendFormat": "{{datname}}:{{relname}}"
      }
     ]
    },
    {
     "title": "UPDATE data",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_updated{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"} ",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Sequential Scans ",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_user_tables_seq_scan{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"}",
       "legendFormat": "{{datname}}: {{relname}}"
      }
     ]
    },
    {
     "title": "DELETE data",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_tup_deleted{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"}",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Low performing queries",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "((pg_stat_statements_shared_blks_hit{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"} !=0 ) / \r\n((pg_stat_statements_shared_blks_read{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"} !=0) +  \r\n (pg_stat_statements_shared_blks_hit{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"} !=0 ))) * 100 < 70",
       "legendFormat": "DB: {{datname}}, Query: {{queryid}} "
      }
     ]
    },
    {
     "title": "Index Scans",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "pg_stat_user_tables_idx_scan{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\", datname=~\"$datname\"}",
       "legendFormat": "{{datname}}: {{relname}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sizing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data and Wal volume size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\", pod=\"$dbserver\", volume='fep-data-volume'} * on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_resource_requests_storage_bytes",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\", pod=\"$dbserver\", volume='fep-wal-volume'} * on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_resource_requests_storage_bytes",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\", pod=\"$dbserver\", volume='fep-log-volume'} * on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_resource_requests_storage_bytes",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\", pod=\"$dbserver\", volume='fep-tablespace-volume'} * on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_resource_requests_storage_bytes",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\", pod=\"$dbserver\", volume='fep-backup-volume'} * on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_resource_requests_storage_bytes",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=\"$namespace\", pod=\"$dbserver\", volume='fep-archivewal-volume'} * on (namespace, persistentvolumeclaim) kube_persistentvolumeclaim_resource_requests_storage_bytes",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Schema sizes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_capacity_schema_size{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"\r}",
       "legendFormat": "{{database_name}}:{{table_schema}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active connection to max connection ratio",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(pg_capacity_connection_total{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}) / (pg_capacity_connection_max{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}) * 100",
       "legendFormat": "$dbserver"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 6, "y": 6 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_connections{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "$dbserver"
      }
     ]
    },
    {
     "title": "Connections in idle state for longer than 1 week",
     "type": "graph",
     "gridPos": { "h": 6, "w": 14, "x": 10, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_capacity_connection_idleintx1week{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"} !=0",
       "legendFormat": "Idle connections on $dbserver"
      }
     ]
    }
   ]
  },
  {
   "title": "Database replication lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replication Lag on Replica ( in seconds)",
     "type": "graph",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
     "repeat": "server",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_replication_lag{namespace=\"$namespace\", service=\"$exporter-service\", server=~\"$dbserver.*\"}",
       "legendFormat": "$dbserver"
      }
     ]
    }
   ]
  }
 ]
}